import type { InterviewQuestion } from '../types/Requirement';

export const BASE_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'auth',
    question: 'Does your app require user login & accounts?',
    subtext: 'This adds authentication screens and JWT/session management',
    type: 'toggle',
    required: true,
    field: 'authRequired',
  },
  {
    id: 'notifications',
    question: 'Do you need push notifications?',
    subtext: 'Alerts for orders, appointments, messages, etc.',
    type: 'toggle',
    required: true,
    field: 'notificationsRequired',
  },
  {
    id: 'offline',
    question: 'Should the app work offline?',
    subtext: 'Local data storage with sync when back online',
    type: 'toggle',
    required: false,
    field: 'offlineSupport',
  },
];

export const INDUSTRY_QUESTIONS: Record<string, InterviewQuestion[]> = {
  'Healthcare': [
    {
      id: 'roles_healthcare',
      question: 'Which portals and dashboards do you need in your hospital app?',
      type: 'multi-select',
      required: true,
      field: 'userRoles',
      options: [
        { label: 'Doctor Portal', value: 'Doctor', icon: '👨‍⚕️', description: 'Schedule slots, write prescriptions, view reports' },
        { label: 'Patient Portal', value: 'Patient', icon: '🤒', description: 'Book appointments, view prescriptions, pay bills' },
        { label: 'Reception Dashboard', value: 'Receptionist', icon: '💼', description: 'Manage schedules and general patient check-ins' },
        { label: 'Pharmacy Dashboard', value: 'Pharmacist', icon: '💊', description: 'Track inventories and dispense prescribed medicines' },
        { label: 'Nurse Portal', value: 'Nurse', icon: '👩‍⚕️', description: 'Log vitals and daily treatment updates' },
        { label: 'System Admin Panel', value: 'Admin', icon: '🏥', description: 'Register doctors, audit logs, and settings config' },
      ],
    },
    {
      id: 'features_healthcare',
      question: 'Which healthcare modules should be enabled?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Appointment Booking', value: 'appointments', icon: '📅', description: 'Online slot booking with calendar' },
        { label: 'Prescription Management', value: 'prescriptions', icon: '💊', description: 'Digital prescriptions and medicine tracking' },
        { label: 'Lab Reports Module', value: 'lab_reports', icon: '🔬', description: 'Upload and view diagnostic test reports' },
        { label: 'Pharmacy & Medicine Inventory', value: 'pharmacy', icon: '🏥', description: 'Track and manage medicine stock' },
        { label: 'Telehealth Video Consultation', value: 'teleconsult', icon: '📹', description: 'Real-time video/chat with doctors' },
        { label: 'Patient Records (EHR)', value: 'ehr', icon: '📋', description: 'Digital health records history logs' },
        { label: 'Analytics & Reports Dashboard', value: 'analytics', icon: '📊', description: 'Hospital performance metric logs' },
      ],
    },
    {
      id: 'payment',
      question: 'Do you need billing & online payments?',
      subtext: 'Invoice generation, Stripe payment gateway integration',
      type: 'toggle',
      required: true,
      field: 'paymentRequired',
    },
    {
      id: 'location_hc',
      question: 'Do you need GPS tracking for ambulances / emergency contacts?',
      subtext: 'Tracks live coordinates on map visual widgets',
      type: 'toggle',
      required: false,
      field: 'locationRequired',
    },
    {
      id: 'multi_language',
      question: 'Enable Multi-Language support?',
      subtext: 'Translates layouts, input fields, and alerts for diverse patients',
      type: 'toggle',
      required: false,
      field: 'multi_language',
    },
  ],

  'Education': [
    {
      id: 'features_education',
      question: 'Which learning features do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Live Classes', value: 'live_classes', icon: '📺', description: 'Real-time video lectures' },
        { label: 'Recorded Videos', value: 'video_library', icon: '🎬', description: 'Pre-recorded course content' },
        { label: 'Quizzes & Exams', value: 'quizzes', icon: '📝', description: 'Auto-graded assessments' },
        { label: 'Assignments', value: 'assignments', icon: '📚', description: 'Submit and grade work' },
        { label: 'Attendance Tracking', value: 'attendance', icon: '✅', description: 'Mark and view attendance' },
        { label: 'Grade Book', value: 'grades', icon: '🎓', description: 'View and manage student grades' },
        { label: 'Fee Management', value: 'fees', icon: '💳', description: 'Fee collection and receipts' },
        { label: 'Parent Portal', value: 'parent_portal', icon: '👨‍👧', description: 'Parents monitor progress' },
      ],
    },
    {
      id: 'payment_edu',
      question: 'Does your app need fee/payment collection?',
      type: 'toggle',
      required: true,
      field: 'paymentRequired',
    },
    {
      id: 'roles_education',
      question: 'Who will use this app?',
      type: 'multi-select',
      required: true,
      field: 'userRoles',
      options: [
        { label: 'Student', value: 'Student', icon: '🧑‍🎓' },
        { label: 'Teacher', value: 'Teacher', icon: '👩‍🏫' },
        { label: 'Admin', value: 'Admin', icon: '🏫' },
        { label: 'Parent', value: 'Parent', icon: '👨‍👧' },
        { label: 'Principal', value: 'Principal', icon: '🎓' },
      ],
    },
  ],

  'E-Commerce': [
    {
      id: 'features_ecommerce',
      question: 'Which store features do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Product Catalog', value: 'catalog', icon: '🛍️', description: 'Browse and filter products' },
        { label: 'Shopping Cart', value: 'cart', icon: '🛒', description: 'Add to cart and checkout' },
        { label: 'Order Tracking', value: 'order_tracking', icon: '📦', description: 'Real-time order status' },
        { label: 'Wishlist', value: 'wishlist', icon: '❤️', description: 'Save favourite items' },
        { label: 'Reviews & Ratings', value: 'reviews', icon: '⭐', description: 'Product review system' },
        { label: 'Coupons & Discounts', value: 'coupons', icon: '🏷️', description: 'Promo codes and offers' },
        { label: 'Seller Dashboard', value: 'seller', icon: '🏪', description: 'For marketplace sellers' },
        { label: 'Analytics', value: 'analytics', icon: '📊', description: 'Sales and traffic reports' },
      ],
    },
    {
      id: 'payment_ecommerce',
      question: 'Which payment methods do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Credit/Debit Card', value: 'card_payment', icon: '💳' },
        { label: 'UPI / Digital Wallet', value: 'upi', icon: '📱' },
        { label: 'Cash on Delivery', value: 'cod', icon: '💵' },
        { label: 'Net Banking', value: 'net_banking', icon: '🏦' },
        { label: 'Buy Now Pay Later', value: 'bnpl', icon: '🔄' },
      ],
    },
  ],

  'Food & Delivery': [
    {
      id: 'features_food',
      question: 'Which delivery features do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Restaurant Listing', value: 'restaurants', icon: '🍽️' },
        { label: 'Menu Management', value: 'menu', icon: '📋' },
        { label: 'Cart & Checkout', value: 'cart', icon: '🛒' },
        { label: 'Live Order Tracking', value: 'gps_tracking', icon: '📍' },
        { label: 'Driver App', value: 'driver', icon: '🚗' },
        { label: 'Reviews & Ratings', value: 'reviews', icon: '⭐' },
        { label: 'Loyalty Points', value: 'loyalty', icon: '🎁' },
        { label: 'Scheduled Orders', value: 'scheduled', icon: '📅' },
      ],
    },
    {
      id: 'location_food',
      question: 'Does this app need GPS / real-time location?',
      type: 'toggle',
      required: true,
      field: 'locationRequired',
    },
  ],

  'Transportation': [
    {
      id: 'features_transport',
      question: 'What type of ride/transport service is this?',
      type: 'single-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Taxi / Ride Hailing', value: 'taxi', icon: '🚕', description: 'Like Uber/Ola' },
        { label: 'Bike Sharing', value: 'bike_share', icon: '🚲', description: 'Dock or dockless bikes' },
        { label: 'Bus / Shuttle', value: 'shuttle', icon: '🚌', description: 'Fixed route services' },
        { label: 'Logistics / Delivery', value: 'logistics', icon: '🚚', description: 'Goods transportation' },
        { label: 'Carpooling', value: 'carpool', icon: '👥', description: 'Shared rides' },
      ],
    },
    {
      id: 'location_transport',
      question: 'Real-time GPS tracking required?',
      type: 'toggle',
      required: true,
      field: 'locationRequired',
    },
  ],

  'Finance & Banking': [
    {
      id: 'features_finance',
      question: 'Which financial features do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Account Dashboard', value: 'dashboard', icon: '📊' },
        { label: 'Fund Transfer', value: 'transfer', icon: '💸' },
        { label: 'Bill Payments', value: 'bill_pay', icon: '📝' },
        { label: 'Investment Portfolio', value: 'investments', icon: '📈' },
        { label: 'Expense Tracker', value: 'expense', icon: '💰' },
        { label: 'Loan Management', value: 'loans', icon: '🏦' },
        { label: 'KYC Verification', value: 'kyc', icon: '🪪' },
        { label: 'Biometric Login', value: 'biometric', icon: '👆' },
      ],
    },
  ],

  'Real Estate': [
    {
      id: 'features_realestate',
      question: 'Which real estate features do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Property Listings', value: 'listings', icon: '🏠' },
        { label: 'Map View', value: 'map', icon: '🗺️' },
        { label: 'Virtual Tours', value: 'virtual_tour', icon: '🏡' },
        { label: 'Agent Profiles', value: 'agents', icon: '👔' },
        { label: 'EMI Calculator', value: 'emi', icon: '🧮' },
        { label: 'Favorites / Shortlist', value: 'favorites', icon: '❤️' },
        { label: 'Document Upload', value: 'documents', icon: '📄' },
      ],
    },
    {
      id: 'location_realestate',
      question: 'Does your app need map/location search?',
      type: 'toggle',
      required: true,
      field: 'locationRequired',
    },
  ],

  'Social Media': [
    {
      id: 'features_social',
      question: 'Which social features do you need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'Feed / Timeline', value: 'feed', icon: '📰' },
        { label: 'Stories', value: 'stories', icon: '⭕' },
        { label: 'Reels / Short Videos', value: 'reels', icon: '🎬' },
        { label: 'Direct Messages', value: 'dm', icon: '💬' },
        { label: 'Groups / Communities', value: 'groups', icon: '👥' },
        { label: 'Live Streaming', value: 'live', icon: '🔴' },
        { label: 'Marketplace', value: 'marketplace', icon: '🛒' },
        { label: 'Content Monetization', value: 'monetization', icon: '💰' },
      ],
    },
  ],

  'Custom': [
    {
      id: 'features_custom',
      question: 'Which core features does your app need?',
      type: 'multi-select',
      required: true,
      field: 'features',
      options: [
        { label: 'User Dashboard', value: 'dashboard', icon: '📊' },
        { label: 'User Profiles', value: 'profiles', icon: '👤' },
        { label: 'Search & Filter', value: 'search', icon: '🔍' },
        { label: 'In-app Messaging', value: 'chat', icon: '💬' },
        { label: 'Payments', value: 'payments', icon: '💳' },
        { label: 'File Uploads', value: 'files', icon: '📎' },
        { label: 'Maps & Location', value: 'maps', icon: '🗺️' },
        { label: 'Reports & Analytics', value: 'analytics', icon: '📈' },
      ],
    },
  ],
};
