/**
 * AppForge-AI — Blueprint Exporter
 * 
 * Exports an AppBlueprint to various formats for download or external tools.
 */

import type { AppBlueprint, ApiEndpoint } from './schema';
import { serializeBlueprint } from './parser';

// ─── JSON Export ─────────────────────────────────────────────────────────────

export function exportBlueprintAsJson(blueprint: AppBlueprint): string {
  return serializeBlueprint(blueprint);
}

// ─── Markdown Export ─────────────────────────────────────────────────────────

export function exportBlueprintAsMarkdown(blueprint: AppBlueprint): string {
  const lines: string[] = [];

  lines.push(`# ${blueprint.name} — App Blueprint`);
  lines.push('');
  lines.push(`> **Industry**: ${blueprint.industry} | **Type**: ${blueprint.appType}`);
  lines.push(`> **Version**: ${blueprint.version} | **Generated by AppForge-AI**`);
  lines.push('');
  lines.push('---');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(blueprint.description || '_No description provided._');
  lines.push('');
  lines.push(`- **User Roles**: ${blueprint.users.join(', ')}`);
  lines.push(`- **Auth Required**: ${blueprint.authRequired ? 'Yes' : 'No'}`);
  lines.push(`- **Navigation**: ${blueprint.navigation.type}`);
  lines.push(`- **Database**: ${blueprint.database.dbType.toUpperCase()}`);
  lines.push('');

  // Screens
  lines.push('## Screens');
  lines.push('');
  blueprint.screens.forEach((screen) => {
    lines.push(`### ${screen.name}`);
    lines.push(`- **Route**: \`${screen.route}\``);
    lines.push(`- **Type**: ${screen.type}`);
    lines.push(`- **Roles**: ${screen.userRoles.join(', ')}`);
    if (screen.description) lines.push(`- **Description**: ${screen.description}`);
    if (screen.components.length > 0) {
      lines.push(`- **Components**: ${screen.components.map(c => c.type).join(', ')}`);
    }
    lines.push('');
  });

  // Database
  lines.push('## Database');
  lines.push('');
  if (blueprint.database.tables.length === 0) {
    lines.push('_No tables defined yet._');
  } else {
    blueprint.database.tables.forEach((table) => {
      lines.push(`### Table: \`${table.name}\``);
      if (table.comment) lines.push(`> ${table.comment}`);
      lines.push('');
      lines.push('| Field | Type | Nullable | Notes |');
      lines.push('|-------|------|----------|-------|');
      table.fields.forEach((f) => {
        const notes = [
          f.primaryKey ? 'PK' : '',
          f.autoIncrement ? 'AUTO_INCREMENT' : '',
          f.unique ? 'UNIQUE' : '',
          f.defaultValue ? `DEFAULT: ${f.defaultValue}` : '',
        ].filter(Boolean).join(', ');
        lines.push(`| ${f.name} | ${f.type}${f.length ? `(${f.length})` : ''} | ${f.nullable ? 'YES' : 'NO'} | ${notes} |`);
      });
      lines.push('');
    });

    if (blueprint.database.relationships.length > 0) {
      lines.push('### Relationships');
      lines.push('');
      blueprint.database.relationships.forEach((r) => {
        lines.push(`- \`${r.from}\` **${r.type}** \`${r.to}\`${r.through ? ` (via \`${r.through}\`)` : ''}`);
      });
      lines.push('');
    }
  }

  // API
  lines.push('## API Endpoints');
  lines.push('');
  lines.push(`**Base URL**: \`${blueprint.api.baseUrl}\``);
  lines.push(`**Auth Scheme**: ${blueprint.api.authScheme.toUpperCase()}`);
  lines.push('');

  if (blueprint.api.endpoints.length === 0) {
    lines.push('_No endpoints defined yet._');
  } else {
    const grouped: Record<string, ApiEndpoint[]> = {};
    blueprint.api.endpoints.forEach((ep) => {
      if (!grouped[ep.tag]) grouped[ep.tag] = [];
      grouped[ep.tag].push(ep);
    });

    Object.entries(grouped).forEach(([tag, endpoints]) => {
      lines.push(`### ${tag}`);
      lines.push('');
      endpoints.forEach((ep) => {
        lines.push(`#### \`${ep.method} ${ep.path}\``);
        lines.push(`${ep.summary}`);
        lines.push(`- **Auth**: ${ep.auth}${ep.role ? ` (${ep.role})` : ''}`);
        lines.push('');
      });
    });
  }

  // Business Logic
  if (blueprint.businessLogic.length > 0) {
    lines.push('## Business Logic Flows');
    lines.push('');
    blueprint.businessLogic.forEach((flow) => {
      lines.push(`### ${flow.name}`);
      lines.push(`> **Trigger**: ${flow.trigger}`);
      lines.push('');
      flow.steps.forEach((step, i) => {
        lines.push(`${i + 1}. **[${step.actor}]** ${step.action} → _${step.outcome}_`);
      });
      lines.push('');
    });
  }

  // Theme
  lines.push('## Theme');
  lines.push('');
  lines.push(`- **Mode**: ${blueprint.theme.mode}`);
  lines.push(`- **Primary Color**: \`${blueprint.theme.colors.primary}\``);
  lines.push(`- **Font Family**: ${blueprint.theme.typography.fontFamily}`);
  lines.push(`- **Icon Set**: ${blueprint.theme.iconSet}`);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(`_Generated by AppForge-AI on ${new Date().toLocaleString()}_`);

  return lines.join('\n');
}

// ─── SQL Export ──────────────────────────────────────────────────────────────

export function exportBlueprintAsSQL(blueprint: AppBlueprint): string {
  const lines: string[] = [];
  const dbType = blueprint.database.dbType;

  lines.push(`-- ${blueprint.name} Database Schema`);
  lines.push(`-- Generated by AppForge-AI on ${new Date().toISOString()}`);
  lines.push(`-- Database: ${dbType.toUpperCase()}`);
  lines.push('');

  if (dbType === 'mysql' || dbType === 'postgresql') {
    lines.push(`CREATE DATABASE IF NOT EXISTS ${blueprint.packageName.replace(/\./g, '_')};`);
    lines.push(`USE ${blueprint.packageName.replace(/\./g, '_')};`);
    lines.push('');
  }

  blueprint.database.tables.forEach((table) => {
    lines.push(`-- ${table.comment || table.name}`);
    lines.push(`CREATE TABLE IF NOT EXISTS \`${table.name}\` (`);

    const fieldLines: string[] = [];
    const pkFields: string[] = [];

    table.fields.forEach((field) => {
      let line = `  \`${field.name}\` `;

      // Type mapping
      switch (field.type) {
        case 'INTEGER': line += 'INT'; break;
        case 'BIGINT': line += 'BIGINT'; break;
        case 'VARCHAR': line += `VARCHAR(${field.length || 255})`; break;
        case 'TEXT': line += 'TEXT'; break;
        case 'BOOLEAN': line += dbType === 'postgresql' ? 'BOOLEAN' : 'TINYINT(1)'; break;
        case 'DECIMAL': line += 'DECIMAL(10,2)'; break;
        case 'FLOAT': line += 'FLOAT'; break;
        case 'DATE': line += 'DATE'; break;
        case 'DATETIME': line += 'DATETIME'; break;
        case 'TIMESTAMP': line += 'TIMESTAMP'; break;
        case 'JSON': line += dbType === 'postgresql' ? 'JSONB' : 'JSON'; break;
        case 'UUID': line += dbType === 'postgresql' ? 'UUID' : 'VARCHAR(36)'; break;
        case 'ENUM': line += `ENUM(${(field.enumValues || []).map(v => `'${v}'`).join(', ')})`; break;
        default: line += field.type;
      }

      if (field.primaryKey) pkFields.push(field.name);
      if (field.autoIncrement) line += dbType === 'postgresql' ? ' GENERATED ALWAYS AS IDENTITY' : ' AUTO_INCREMENT';
      if (!field.nullable) line += ' NOT NULL';
      if (field.unique && !field.primaryKey) line += ' UNIQUE';
      if (field.defaultValue !== undefined && field.defaultValue !== null) {
        line += ` DEFAULT ${field.defaultValue}`;
      }
      if (field.comment) line += ` COMMENT '${field.comment}'`;

      fieldLines.push(line);
    });

    if (pkFields.length > 0) {
      fieldLines.push(`  PRIMARY KEY (${pkFields.map(f => `\`${f}\``).join(', ')})`);
    }

    // Foreign keys
    if (table.foreignKeys) {
      table.foreignKeys.forEach((fk) => {
        fieldLines.push(
          `  FOREIGN KEY (\`${fk.field}\`) REFERENCES \`${fk.referencesTable}\`(\`${fk.referencesField}\`) ON DELETE ${fk.onDelete} ON UPDATE ${fk.onUpdate}`
        );
      });
    }

    lines.push(fieldLines.join(',\n'));
    lines.push(');');
    lines.push('');

    // Indexes
    if (table.indexes) {
      table.indexes.forEach((idx) => {
        lines.push(
          `CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX \`${idx.name}\` ON \`${table.name}\` (${idx.fields.map(f => `\`${f}\``).join(', ')});`
        );
      });
      lines.push('');
    }
  });

  return lines.join('\n');
}

// ─── OpenAPI Export ──────────────────────────────────────────────────────────

export function exportBlueprintAsOpenAPI(blueprint: AppBlueprint): string {
  const spec: any = {
    openapi: '3.0.0',
    info: {
      title: `${blueprint.name} API`,
      version: blueprint.api.version,
      description: blueprint.description,
    },
    servers: [
      { url: blueprint.api.baseUrl, description: 'API Server' }
    ],
    tags: [],
    paths: {},
    components: {
      securitySchemes: {},
    },
  };

  if (blueprint.api.authScheme === 'jwt') {
    spec.components.securitySchemes.BearerAuth = {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT',
    };
  }

  const tags = new Set<string>();

  blueprint.api.endpoints.forEach((ep) => {
    tags.add(ep.tag);

    if (!spec.paths[ep.path]) spec.paths[ep.path] = {};

    const operation: any = {
      tags: [ep.tag],
      summary: ep.summary,
      description: ep.description || '',
      operationId: ep.id,
      responses: {
        [ep.responseCode]: { description: 'Success' },
        '400': { description: 'Bad Request' },
        '401': { description: 'Unauthorized' },
        '500': { description: 'Internal Server Error' },
      },
    };

    if (ep.auth !== 'public') {
      operation.security = [{ BearerAuth: [] }];
    }

    if (ep.requestBody && ep.requestBody.length > 0) {
      operation.requestBody = {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: Object.fromEntries(
                ep.requestBody.map(f => [f.name, { type: f.type || 'string', description: f.description }])
              ),
              required: ep.requestBody.filter(f => f.required).map(f => f.name),
            },
          },
        },
      };
    }

    spec.paths[ep.path][ep.method.toLowerCase()] = operation;
  });

  tags.forEach((t) => spec.tags.push({ name: t }));

  return JSON.stringify(spec, null, 2);
}

// ─── Trigger Download ─────────────────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadBlueprintJson(blueprint: AppBlueprint): void {
  downloadFile(exportBlueprintAsJson(blueprint), `${blueprint.name.replace(/\s/g, '_')}_blueprint.json`, 'application/json');
}

export function downloadBlueprintMarkdown(blueprint: AppBlueprint): void {
  downloadFile(exportBlueprintAsMarkdown(blueprint), `${blueprint.name.replace(/\s/g, '_')}_blueprint.md`, 'text/markdown');
}

export function downloadBlueprintSQL(blueprint: AppBlueprint): void {
  downloadFile(exportBlueprintAsSQL(blueprint), `${blueprint.name.replace(/\s/g, '_')}_schema.sql`, 'text/plain');
}

export function downloadBlueprintOpenAPI(blueprint: AppBlueprint): void {
  downloadFile(exportBlueprintAsOpenAPI(blueprint), `${blueprint.name.replace(/\s/g, '_')}_openapi.json`, 'application/json');
}
